name: CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ["2.6", "2.7", "3.0", "3.1"]
        rspec-version: ["2_x", "3_0", "3_1", "3_2", "3_3", "3_4", "3_5", "3_6", "3_7", "3_8", "3_9", "3_10"]

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/rspec_${{ matrix.rspec-version }}.gemfile

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ruby-${{ matrix.ruby-version }}-rspec-${{ matrix.rspec-version }}
        path: tmp

  post-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: test-artifacts
          separate-directories: true
          delete-merged: true
