name: CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    name: "test (ruby: ${{ matrix.ruby-version}}, rspec: ${{ matrix.rspec-version }})"
    strategy:
      matrix:
        ruby-version: ["2.6", "2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]
        rspec-version: ["3_4", "3_5", "3_6", "3_7", "3_8", "3_9", "3_10", "3_11", "3_12", "3_13"]
        include:
          # NOTE: ruby 3.2+ is not compatible with rspec < 3.4
          - { ruby-version: "2.6", rspec-version: "2_x" }
          - { ruby-version: "2.7", rspec-version: "2_x" }
          - { ruby-version: "3.0", rspec-version: "2_x" }
          - { ruby-version: "3.1", rspec-version: "2_x" }
          - { ruby-version: "2.6", rspec-version: "3_0" }
          - { ruby-version: "2.7", rspec-version: "3_0" }
          - { ruby-version: "3.0", rspec-version: "3_0" }
          - { ruby-version: "3.1", rspec-version: "3_0" }
          - { ruby-version: "2.6", rspec-version: "3_1" }
          - { ruby-version: "2.7", rspec-version: "3_1" }
          - { ruby-version: "3.0", rspec-version: "3_1" }
          - { ruby-version: "3.1", rspec-version: "3_1" }
          - { ruby-version: "2.6", rspec-version: "3_2" }
          - { ruby-version: "2.7", rspec-version: "3_2" }
          - { ruby-version: "3.0", rspec-version: "3_2" }
          - { ruby-version: "3.1", rspec-version: "3_2" }
          - { ruby-version: "2.6", rspec-version: "3_3" }
          - { ruby-version: "2.7", rspec-version: "3_3" }
          - { ruby-version: "3.0", rspec-version: "3_3" }
          - { ruby-version: "3.1", rspec-version: "3_3" }

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/rspec_${{ matrix.rspec-version }}.gemfile

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ruby-${{ matrix.ruby-version }}-rspec-${{ matrix.rspec-version }}
        path: tmp

  post-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: test-artifacts
          separate-directories: true
          delete-merged: true
